# Generated by Django 4.1.2 on 2023-04-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_list',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=30)),
                ('portrait', models.CharField(default='https://i.pinimg.com/564x/e3/82/55/e38255b8fad2209e3f0252e8b4ba0612.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('reason', models.CharField(max_length=500)),
                ('at', models.DateTimeField()),
                ('number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Lang_list',
            fields=[
                ('language', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('studio', models.CharField(max_length=30)),
                ('ageplus', models.PositiveIntegerField()),
                ('run_time', models.TimeField()),
                ('portrait', models.CharField(default='https://i.pinimg.com/564x/e3/82/55/e38255b8fad2209e3f0252e8b4ba0612.jpg', max_length=200)),
                ('landscape', models.CharField(default='https://wallpapercave.com/wp/wp7955488.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('v_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sum', models.FloatField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating', models.FloatField()),
                ('rorb_id', models.AutoField(primary_key=True, serialize=False)),
                ('rby', models.ForeignKey(db_column='rby', on_delete=django.db.models.deletion.CASCADE, to='movies.users')),
                ('ron', models.ForeignKey(db_column='ron', on_delete=django.db.models.deletion.CASCADE, to='movies.views')),
            ],
            options={
                'unique_together': {('ron', 'rby')},
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='movies.lang_list')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('m_id', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_id', models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.CASCADE, to='movies.catalog')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('m_id', 'director_id')},
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='movies.cat_list')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('m_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('actress_id', models.ForeignKey(db_column='actress_id', on_delete=django.db.models.deletion.CASCADE, to='movies.catalog')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('m_id', 'actress_id')},
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_id', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, to='movies.catalog')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('m_id', 'actor_id')},
            },
        ),
    ]
