# Generated by Django 4.1.2 on 2023-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='views',
            old_name='v_id',
            new_name='m_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
