# Generated by Django 4.1.2 on 2023-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_v_id_views_m_id_alter_movie_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
