# Generated by Django 4.1.2 on 2023-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
